#====================================================================
# File automatically generated by ES3  
# This file regenerated each time you run EISC Studio, so save under a 
# new name if you hand edit, or it will be overwritten.
#				www.adc.co.kr
#====================================================================



ECHO	=	echo.exe
CC	=	ae32000-elf-gcc
AS	=	ae32000-elf-as
LD	=	ae32000-elf-ld
AR	=	ae32000-elf-ar
OBJCOPY	=	ae32000-elf-objcopy
OBJDUMP	=	ae32000-elf-objdump
CFLAGS	=	 -O2  -g -w -Wall 
ASFLAGS	=	 -gstabs 
LDFLAGS	=	-Wall -nostartfiles -lgcc -lc -lm
DISFLAGS	=	-dzShxl
ARFLAGS	=	rcusv
#====== Directory =====
OUTPUTDIR	=	output/
OBJDIR	=	obj/
INCDIR	=	\
	 -I"../../include"
LIBDIR	=	
LIBS	=	\
	../../lib/libadStar.a\
	../../lib/libjpeg.a\
	../../lib/libmad.a\
	../../lib/libpng.a\
	../../lib/libz.a

SOURCES	 += ../../startup/adStarInit.c
SOURCES	 += ../../startup/startup_adstar.s
SOURCES	 += main.c
SOURCES	 += rsp_main.c
SOURCES	 += ../../etc_driver/misc.c
SOURCES	 += mass_stor.c
SOURCES	 += ../drive/smart_bed_remocon.c
SOURCES	 += ../drive/lcd.c

OBJECTS	 += ${OBJDIR}adStarInit.o
OBJECTS	 += ${OBJDIR}startup_adstar.o
OBJECTS	 += ${OBJDIR}main.o
OBJECTS	 += ${OBJDIR}rsp_main.o
OBJECTS	 += ${OBJDIR}misc.o
OBJECTS	 += ${OBJDIR}mass_stor.o
OBJECTS	 += ${OBJDIR}smart_bed_remocon.o
OBJECTS	 += ${OBJDIR}lcd.o

DEPS	 += ${OBJDIR}adStarInit.d
DEPS	 += ${OBJDIR}startup_adstar.d
DEPS	 += ${OBJDIR}main.d
DEPS	 += ${OBJDIR}rsp_main.d
DEPS	 += ${OBJDIR}misc.d
DEPS	 += ${OBJDIR}mass_stor.d
DEPS	 += ${OBJDIR}smart_bed_remocon.d
DEPS	 += ${OBJDIR}lcd.d



#====== TAGET Define =====
TARGET	=	$(OUTPUTDIR)bootloader.elf

BINARY	=	$(TARGET).bin

HEX	=	$(TARGET).hex

DISASSEMBLE	=	$(TARGET).dis

ALL	:	$(TARGET) $(BINARY) 

all	:	$(TARGET) $(BINARY) 

binary	:	$(BINARY)

bin	:	$(BINARY)

hex	:	$(HEX)

disassemble	:	$(DISASSEMBLE)

dis	:	$(DISASSEMBLE)

clean	:
	@$(ECHO) 'Deleting intermediate and output files... '
	rm -f $(OBJECTS) $(TARGET) $(DISASSEMBLE) $(BINARY) $(DEPS)
	@$(ECHO) ' '

cleanall	:
	@$(ECHO) 'Deleting intermediate and output files... '
	rm -f $(OBJECTS) $(TARGET) $(DISASSEMBLE) $(BINARY) $(DEPS)
	@$(ECHO) ' '

cleanobj	:
	@$(ECHO) 'Deleting intermediate files... '
	rm -f $(OBJECTS) 
	@$(ECHO) ' '

cleanbin	:
	rm -f $(BINARY)
	@$(ECHO) ' '

cleandis	:
	rm -f $(DISASSEMBLE)
	@$(ECHO) ' '

ifeq ($(FULLMSG),no)
ECHOMARK = @
else
ECHOMARK = 
endif

-include ${OBJDIR}adStarInit.d
-include ${OBJDIR}startup_adstar.d
-include ${OBJDIR}main.d
-include ${OBJDIR}rsp_main.d
-include ${OBJDIR}misc.d
-include ${OBJDIR}mass_stor.d
-include ${OBJDIR}smart_bed_remocon.d
-include ${OBJDIR}lcd.d

#============= TARGET ====================
${TARGET} : Makefile.mk ${OBJECTS} ${LIBS} adstar-bootloader.ld
	@$(ECHO) 'Linking...'
	$(ECHOMARK)$(CC) -o $(TARGET) $(OBJECTS) $(LIBDIR) -Xlinker --start-group $(LIBS) -Xlinker --end-group $(LDFLAGS) -Xlinker -T"adstar-bootloader.ld"
	@$(ECHO) 'Finished building : $@ '
	@$(ECHO) ' '

$(BINARY): $(TARGET)
	@$(ECHO) 'Generating binary file...'
	$(ECHOMARK)$(OBJCOPY) -O binary $(TARGET) $@
	@$(ECHO) 'Finished building : $@ '
	@$(ECHO) ' '
	@$(ECHO) 'Program section information '
	$(ECHOMARK)size $(TARGET)
	@$(ECHO) ' '

$(DISASSEMBLE) : $(TARGET)
	@$(ECHO) 'Generating disassemble file...'
	$(ECHOMARK)$(OBJDUMP) $(DISFLAGS) $(TARGET) > $@ 
	@$(ECHO) 'Finished building : $@ '
	@$(ECHO) ' '

${OBJDIR}adStarInit.o : ../../startup/adStarInit.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$@" -o "$@" "$<"

${OBJDIR}startup_adstar.o : ../../startup/startup_adstar.s
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) -Wa,$(ASFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$@" -o "$@" "$<"

${OBJDIR}main.o : main.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$@" -o "$@" "$<"

${OBJDIR}rsp_main.o : rsp_main.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$@" -o "$@" "$<"

${OBJDIR}misc.o : ../../etc_driver/misc.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$@" -o "$@" "$<"

${OBJDIR}mass_stor.o : mass_stor.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$@" -o "$@" "$<"

${OBJDIR}smart_bed_remocon.o : ../drive/smart_bed_remocon.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$@" -o "$@" "$<"

${OBJDIR}lcd.o : ../drive/lcd.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$@" -o "$@" "$<"

